export enum LanguageEnum {
  turkce = 'Türkçe',
  ingilizce = 'İngilizce',
  almanca = 'Almanca',
  arapca = 'Arapça',
  rusca = 'Rusça',
  ispanyolca = 'İspanyolca',
  fransizca = 'Fransızca',
  italyanca = 'İtalyanca',
  farsca = 'Farsça',
  portekizce =  'Portekizce',
  cince = 'Çince',
  japonca = 'Japonca',
  korece = 'Korece',
  flemenkce = 'Flemenkçe',
  hintce = 'Hintçe',
  ibranice = 'İbranice',
  azerice = 'Azerice',
}
